### ISSUE TITLE
Set up backend data hosting

### ISSUE THREAD

**Issue by dakriy** [blakestone95/73rdLegionWebsite#17]
Set up a back end database service. MySQL has been decided because of its balance between ease and reliability, and extra data protection. 

Acceptance Criteria

* Setup a MySQL database server in the backend
* Configure Laravel to access it.
* Write documentation on how to set it up for dev environments.

**Comment by blakestone95** [comment]
I'll try it out first before I close this issue.

**Comment by dakriy** [comment]
Oh... ok.
